### ISSUE TITLE
Attack.js: Attacks don't load sometimes 

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#1]
Sometimes, after pressing "Press this to find a pokemon" button, doesn't load attacks for both the enemy and use pokemon. 

## Technical details:
The attacks are being fetched from PokeApi in JavaScript array using, XHttpRequest.

**Comment by narenbakshi97** [comment]
For now, we can press the button again for another wild encounter

**Comment by tinchods93** [comment]
Hello! Would you kindly assignme this issue? I already found the problem but i'm trying to figured out how to solve it.

This function right here, sometimes gets an undefined object so the entire skill tree gets undefined and doesnt show the skills.
![image](https://user-images.githubusercontent.com/35530927/108639048-338df580-7471-11eb-9452-b3fac698e8eb.png)

**Comment by narenbakshi97** [comment]
Hmm, that's good debugging! Thank you.
