### ISSUE TITLE
UI Issue: The main game layout is shifted down and unnecessary blank space on top

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#20]
**Describe the bug**
After selecting your starter Pokemon the main game starts with some amount of top margin value, which shifts our whole game/layout to the bottom, starting with extra unnecessary space on the top

**To Reproduce**
1. Press the Start button
2. Choose the starter Pokemon
3. The White section created on the top of the game is our bug

**Expected behavior**
There should be no extra white space on top and the game should start with the title in the top corner

**Comment by Aishu21** [comment]
Can I work on this issue ?
