### ISSUE TITLE
Put the status below user pokemon attacks

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#25]
**Describe the bug**
The status shows us the battle description, which pokemon used which move, how much experience did the user pokemon got, what is the pokeball status after throwing, etc. 
Since it is on top left corner, it's not convinient for the user to see the status while playing, it would be better if like the actual Pokemon games, we put the status on the left corner below the user pokemon attacks so without changing the eye-ball, user can view the status and choose the attack

**Additional context**
In the Index.html page, search for #status Id,
your task is to put it inside #screen ID division,
below #user,
now don't simply cut and paste but see if you can make it more user-friendly

**Comment by Aishu21** [comment]
Can I work on this issue ?

**Comment by narenbakshi97** [comment]
Assigned to you!

**Comment by narenbakshi97** [comment]
Hi, the status looks really good, the only problem is with the boxes below the battle screen when we are not battling, they are coming way up crossing the battle screen border, would you like to work on that or should I create a new issue.

**Comment by Aishu21** [comment]
Thanks !
Please create a new issue I will work on it.

Regards,
Priyanka Bhosale.

**Comment by narenbakshi97** [comment]
#39
