### ISSUE TITLE
Reset Status after loosing the Battle

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#28]
**Describe the bug**
If we lose in battle, the status (the green text of the upper left corner) still shows the last attack of the enemy pokemon

**To Reproduce**
1. Play a battle
2. Once you get defeated and get the alert message
3. The status will be still showing the last attack by the foe

**Expected behavior**
It should be blank if no battle is happening

**Comment by nicocarnebia** [comment]
I would like to help

**Comment by narenbakshi97** [comment]
Go ahead!
