### ISSUE TITLE
Add a mute button on the start screen

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#29]
**Is your feature request related to a problem? Please describe.**
No

**Comment by 96RadhikaJadhav** [comment]
@narenbakshi97  Can I work on it?

**Comment by narenbakshi97** [comment]
Happy coding!

**Comment by Aishu21** [comment]
Can I work on this issue?

**Comment by narenbakshi97** [comment]
Hi @Aishu21, this task is already assigned but there are many other issues you can help us with, many of them are beginner friendly as well

**Comment by 96RadhikaJadhav** [comment]
@narenbakshi97 I'm sorry, I have tried but the code seems to be not working for me. You can assign the issue to someone else.

**Comment by narenbakshi97** [comment]
no problem, thanks for letting me know

**Comment by Aishu21** [comment]
Assign it to me .

**Comment by nicocarnebia** [comment]
Can i work on this one?
