### ISSUE TITLE
Pikachu sound not getting played/loaded after selecting it as starter

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#36]
**Describe the bug**
[ERROR MSG]: *Resource not found error: /Pokemon-Simulator/sounds/0025%20-%20Pikachu.wav:1* 

**To Reproduce**
1. Select Pikachu as your starter
2. Press submit
3. Unlike the other starters, the sound won't play for Pikachu

**Expected behavior**
Pikachu sound played when main screen started

**Additional context**
Sounds plays when you catch a new pokemon select it as your main pokemon and switch back to Pikachu

**Comment by 96RadhikaJadhav** [comment]
@narenbakshi97 I have created a PR. Please check and let me know if it's fine.

**Comment by narenbakshi97** [comment]
It's working properly, thanks!
