### ISSUE TITLE
My Bag and Pokemon divisions are crossing the above division border in the main game layout

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#39]
**Describe the bug**
When the battle is not on, the below sections are overlapping inside the pokemon screen

**Comment by Aishu21** [comment]
Assign it to me.

**Comment by Aishu21** [comment]
While trying to push , I am getting this, although yesterday I was able to push :
remote: Permission to narenbakshi97/Pokemon-Simulator.git denied to Aishu21.
fatal: unable to access 'https://github.com/narenbakshi97/Pokemon-Simulator.git/': The requested URL returned error: 403

**Comment by narenbakshi97** [comment]
Make sure you are pushing in the forked repo and not the actual repo. After that, you will send a pull request to merge both

**Comment by Aishu21** [comment]
Actually I cloned new repo to try out with existing changes.. when trying with new repo; I am getting the error . WHen tried with old cloned repo it worked ..

**Comment by narenbakshi97** [comment]
when you clone it, it points to the original repo, so if you push something with destination mentioned as origin, instead of YOU/pkmn, it tries to push to MINE/pkmn, that's why getting 403

**Comment by Aishu21** [comment]
Thanks !.
