### ISSUE TITLE
Background sound doesn't load for the homepage

### ISSUE THREAD

**Issue by narenbakshi97** [narenbakshi97/Pokemon-Simulator#8]
**Describe the bug**
When we first open the website, the starter pokemon appears but the music doesn't play, or very rarely it does.

**To Reproduce**
1. Open the link
2. If the music doesn't start, that's the error

**Expected behavior**
You start the game and a title track should be played while selecting a pokemon

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Chrome

**Smartphone (please complete the following information):**
 - Version: Version 88.0.4324.182 (Official Build) (x86_64)

**Additional context**
N/A

**Comment by tinchods93** [comment]
Hello again... I found that Autoplay on Chrome is disabled, therefore your audio wont be playing automatically. [You can check this link](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).
I would suggest to make a Start button and then, play the intro music, i can do this for you if you like.

**Comment by narenbakshi97** [comment]
Hi, that's a good idea, thanks for sharing the link. 
About your suggestion, creating a button sounds a good idea, make sure:

1. its CSS visibility property is set to hidden
2. The onclick is getting triggered through JavaScript
